function [fitresult, gof] = createFit(ans)
%CREATEFIT(ANS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : ans
%      Y Output: ans
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-May-2016 16:17:13

tmp = ans;
length = size(tmp,1);

% while length >= 1
%     if (tmp(length,4) <= 64 || tmp(length,4) >= 72)
%         tmp(length,:) = [];
%     end;
%     length = length - 1;
% end;

[xData, yData] = prepareCurveData( tmp(:,4), tmp(:,2) );

% Set up fittype and options.
ft = fittype( 'poly2' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Flow - Speed' );
h = plot( fitresult, xData, yData );
legend( h, 'f vs. s', 'Flow - Speed', 'Location', 'NorthEast' );
% Label axes
xlabel Speed
ylabel Flow
grid on


